/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  userSidebar: [
    {
      type: "category",
      label: "User Manual",
      collapsed: false,
      items: [
        "user-manual/introduction",
        "user-manual/resources",
        "user-manual/running",
        "user-manual/starting-project",
        "user-manual/access-control",
        {
          type: "category",
          label: "Exploring the Interface",
          items: [
            {
              type: "category",
              label: "Toolbar",
              items: [
                "user-manual/exploring-interface/toolbar/introduction",
                "user-manual/exploring-interface/toolbar/visualization",
                "user-manual/exploring-interface/toolbar/automatic-annotation",
                "user-manual/exploring-interface/toolbar/export",
              ],
            },
            {
              type: "category",
              label: "Table Viewer",
              items: [
                "user-manual/exploring-interface/table-view/introduction",
                "user-manual/exploring-interface/table-view/search-navigation",
                "user-manual/exploring-interface/table-view/filtering-visibility",
                "user-manual/exploring-interface/table-view/pipeline",
                "user-manual/exploring-interface/table-view/column-header",
              ],
            },
            {
              type: "category",
              label: "Graph Visualization",
              items: [
                "user-manual/exploring-interface/graph-view/introduction",
                "user-manual/exploring-interface/graph-view/graph-area",
                "user-manual/exploring-interface/graph-view/sidebar",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Enrichment Operations",
          items: [
            {
              type: "category",
              label: "Schema Annotation",
              items: [
                "user-manual/enrichment-operations/schema-annotation/automatic-schema-annotation",
                "user-manual/enrichment-operations/schema-annotation/manual-schema-annotation",
              ],
            },
            "user-manual/enrichment-operations/modification",
            {
              type: "category",
              label: "Reconciliation",
              items: [
                "user-manual/enrichment-operations/reconciliation/introduction",
                "user-manual/enrichment-operations/reconciliation/automatic-reconciliation",
                "user-manual/enrichment-operations/reconciliation/service-reconciliation",
                "user-manual/enrichment-operations/reconciliation/manual-reconciliation",
                "user-manual/enrichment-operations/reconciliation/matching-revision",
              ],
            },
            "user-manual/enrichment-operations/extension",
            "user-manual/enrichment-operations/compliance",
            "user-manual/enrichment-operations/generative-ai",
          ],
        },
        {
          type: "category",
          label: "Discover Services",
          items: [
            "user-manual/discover-services/modifiers",
            "user-manual/discover-services/reconcilers",
            "user-manual/discover-services/extenders",
            "user-manual/discover-services/compliance",
            "user-manual/discover-services/generative-ai",
          ],
        },
        "user-manual/known-bugs",
      ],
    },
  ],
  technicalSidebar: [
    {
      type: "category",
      label: "Technical Manual",
      collapsed: false,
      items: [
        "technical-manual/introduction",
        "technical-manual/deploy",
        "technical-manual/architecture",
        "technical-manual/table-representation",
        {
          type: "category",
          label: "Backend",
          items: [
            "technical-manual/backend/log-system",
            {
              type: "category",
              label: "Api Specification",
              items: [
                "technical-manual/backend/api-specifications/routes-overview",
                "technical-manual/backend/api-specifications/save-get-table",
              ],
            },
            {
              type: "category",
              label: "Adding new category",
              items: [
                "technical-manual/backend/adding-new-category/backend",
                "technical-manual/backend/adding-new-category/frontend",
                "technical-manual/backend/adding-new-category/introduction",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Frontend",
          items: [
            "technical-manual/frontend/architecture",
            "technical-manual/frontend/components",
            "technical-manual/frontend/dashboard-components",
            "technical-manual/frontend/metadata-components",
            "technical-manual/frontend/store",
            "technical-manual/frontend/table",
            "technical-manual/frontend/thunk",
          ],
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
