name: Workflow to deploy docs to github pages
on: 
  push:
    branches:
      - main
jobs:
  Deploy-App:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: deploy
        run: |
          cd I2T-docs
          yarn install
          yarn deploy