name: Workflow to deploy docs to github pages
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: I2T-docs
          git-user: ${{ secrets.GIT_USER }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages